import type { Config } from 'tailwindcss';
import { fontFamily } from 'tailwindcss/defaultTheme';
import TailwindAnimate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
const config: Config = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1440px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        primary: '#3376F7',
        secondary: '#F75233',
        tertiary: '#D8F733',
        primaryLight10: '#2a70f8',
        primaryLight9: '#4180f9',
        primaryLight8: '#4d91fa',
        primaryLight7: '#5da3fb',
        primaryLight6: '#6bb5fc',
        primaryLight5: '#80c6fd',
        primaryLight4: '#94d7fe',
        primaryLight3: '#a8e8ff',
        primaryLight2: '#baf9ff',
        primaryLight1: '#d0faff',
        primaryDark10: '#020a19',
        primaryDark9: '#0a1b2b',
        primaryDark8: '#13263d',
        primaryDark7: '#1b3e50',
        primaryDark6: '#243f63',
        primaryDark5: '#2c4f76',
        primaryDark4: '#345789',
        primaryDark3: '#3e5d9c',
        primaryDark2: '#4768af',
        primaryDark1: '#4f73c2',
        secondaryLight10: '#f86347',
        secondaryLight9: '#f9755c',
        secondaryLight8: '#f98670',
        secondaryLight7: '#fa9785',
        secondaryLight6: '#fba999',
        secondaryLight5: '#fcbaad',
        secondaryLight4: '#fdcbc2',
        secondaryLight3: '#fddcd6',
        secondaryLight2: '#feeeeb',
        secondaryLight1: '#ffffff',
        secondaryDark10: '#000000',
        secondaryDark9: '#190805',
        secondaryDark8: '#31100a',
        secondaryDark7: '#4a190f',
        secondaryDark6: '#632114',
        secondaryDark5: '#7c291a',
        secondaryDark4: '#94311f',
        secondaryDark3: '#ad3924',
        secondaryDark2: '#c64229',
        secondaryDark1: '#de4a2e',
        neutral1: '#FFFFFF',
        neutral3: '#F5F5F5',
        neutral4: '#F0F0F0',
        neutral5: '#D9D9D9',
        neutral6: '#BFBFBF',
        neutral7: '#8C8C8C',
        neutral8: '#595959',
        neutral9: '#454545',
        neutral10: '#262626',
        neutral11: '#1F1F1F',
        neutral12: '#141414',
        blue0: '#F9FEFF',
        blue1: '#EDF9FE',
        blue2: '#D5F1FD',
        blue5: '#6FCEF8',
        blue6: '#4FC3F7',
        blue7: '#43A6D2',
        blue8: '#388AAF',
        blue9: '#388AAF',
        blue10: '#24586F',
        error1: '#FDE8E9',
        error6: '#ED1C24',
        error5: '#F0454B',
        error7: '#C9181F',
        green1: '#E6FDF1',
        green5: '#2EEB8F',
        green6: '#00E676',
        green8: '#00A354',
        warning1: '#FFFDE6',
        warning8: '#B5A600',
        white: '#FFFFFF',
        black50: '#918F8F',
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['var(--font-raleway)', ...fontFamily.sans],
        alt: ['var(--font-raleway-alternates)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'spin-slow': {
          '0%': { rotate: '0deg' },
          '100%': { rotate: '360deg' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'spin-slow': 'spin 10s linear infinite',
      },
    },
  },
  plugins: [TailwindAnimate],
};

export default config;
