apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      containers:
      - name: {{ .Values.metadata.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}